#!/bin/sh

[ -r /etc/default/boot-flags ] && . /etc/default/boot-flags

case "${CHECK_BOOT_FLAGS_PARTITION}" in
	[Nn]*)
		exit 0
		;;
esac

if [ -x /usr/bin/bootflag.sh ]; then
	/usr/bin/bootflag.sh
fi
